spring:
  application:
    name: go-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # 초기 개발 중이면 update, DB 완성 돼 있고, 스키마 변경을 원하지 않으면 validate

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
lms:
  file:
    max-file-size: 2MB

server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Swagger UI 경로를 강제 지정
  enable-spring-security: false # Spring Security가 있어도 Swagger는 무인증 상태로 접근 가능

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers,env,beans,mappings"
  endpoint:
    health:
      show-details: always
