spring:
  application:
    name: go-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # 초기 개발 중이면 update, DB완성돼 있고, 스키마 변경을 원하지 않으면 validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
lms:
  file:
    max-file-size: 2MB

server:
  servlet:
    context-path: /api

#encryption:
#  key-url: http://localhost:8500/v1/kv/config/application/encryption.key