server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gokim.cfq4yekgo3ml.ap-northeast-2.rds.amazonaws.com:3306/gokim?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: gokim
    password: gokim1029384756!!

cloud:
  aws:
    s3:
      bucket: gokim-aws-bucket-1029384756
    region:
      static: ap-northeast-2

